# Generated by Django 4.0.5 on 2022-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_news', '0010_alter_category_subscribers_delete_subscribersusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
