# Generated by Django 4.0.5 on 2022-10-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_news', '0011_rename_category_name_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='portal_news.SubscribersUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscribersusers',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_news.category'),
        ),
        migrations.AddField(
            model_name='subscribersusers',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
